export const FETCH_LEGAL_PROVIDERS_START = 'FETCH_LEGAL_PROVIDERS_START';
export const FETCH_LEGAL_PROVIDERS_SUCCESS = 'FETCH_LEGAL_PROVIDERS_SUCCESS';
export const FETCH_LEGAL_PROVIDERS_FAILURE = 'FETCH_LEGAL_PROVIDERS_FAILURE';
export const SET_FILTERED_LEGAL_PROVIDERS = 'SET_FILTERED_LEGAL_PROVIDERS';