export const FETCH_TRANSPARENCY_FIRMS_START = 'FETCH_TRANSPARENCY_FIRMS_START';
export const FETCH_TRANSPARENCY_FIRMS_SUCCESS = 'FETCH_TRANSPARENCY_FIRMS_SUCCESS';
export const FETCH_TRANSPARENCY_FIRMS_FAILURE = 'FETCH_TRANSPARENCY_FIRMS_FAILURE';
export const SET_FILTERED_TRANSPARENCY_FIRMS = 'SET_FILTERED_TRANSPARENCY_FIRMS';
